-- 1.Cho biết Tên lớp học có cấp độ ‘N5’
select TenLop
-- 2.Cho biết tên lớp mà có cấp độ ‘N5’ mà học viên tên ‘Trần Thảo Vân’ đang học
-- 3.Cho biết ngày kết thúc của lớp học có cấp độ ‘N3’ mà thời gian bắt đầu học là tháng 3 năm 2020
-- 4.Cho biết Tên lớp học có mã lớp là ‘JBasic001’
-- 5.Cho biết Tên các lớp học có ngày bắt đầu là 15
-- 6.Cho biết Tên các lớp học có tháng bắt đầu là tháng 3
-- 7.Cho biết Tên lớp học có ngày kết thúc là 15/03/2021
-- 8.Cho biết Tên học viên có mã học viên là ‘HV17524’
-- 9. Cho biết Tên giáo viên có mã giáo viên là ‘GV0324’
-- 10.Cho biết Tên học viên và mã lớp học mà học cấp độ ‘N4’
-- 11. Cho biết Thông tin giáo viên dạy cấp độ ‘N1’
-- 12. Cho biết Thông tin học viên học cấp độ ‘N3’
-- 13. Cho biết Tên học viên tham gia nhiều lớp học nhất của trung tâm
-- 14. Cho biết Tên giáo viên dạy nhiều lớp học nhất của trung tâm
-- 15. Cho biết Trạng thái của lớp có mã cấp độ là ‘JAdvanced231’
